# Your project's details
PROJECT_NAME: Pablo
GITHUB_CURRENT_VERSION: 0.1
GITHUB_PROJECT_URL: https://github.com/dharmafly/pablo

# The style for your site (currently only default)

THEME: ocean

############ Optional extras

GITHUB_ZIP_URL: #https://github.com/dharmafly/dharmafly-docs/zipball/gh-pages
TWITTER_PROJECT_URL: https://twitter.com/dharmafly
# javascript, css or html5
LANG: javascript

# Add your project's scripts here to be available to any examples
SCRIPTS:
- src: https://raw.github.com/dharmafly/pablo/master/pablo.js

# A quote to add at the footer of your project page
QUOTE:
  quote: Painting is just another way of keeping a diary.
  cite: Pablo Picasso

# Your google analytics id
GA_ID:

##############

# Page names -- paths should not be updated and
# are currently hard-coded to match directory names / site categories.
# (They're here as placeholders for future work to
# allow new sections to be dynamically created)
sections:
 - path:
   name: Overview
 - path: reference
   name: Reference

###############################

# Jekyll options

safe:        false
auto:        false
server:      false

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   /:title
baseurl:     /

exclude: ['README.md', 'assets', 'FiddlerRules.farx']
